import { Link } from "@tanstack/react-router";
import { ArrowRight, CheckCircle2, Database, FileSearch, Layers3, Network, ShieldCheck } from "lucide-react";
import { Reveal } from "./Reveal";
import { SectionHead } from "./SectionHead";
import { ProcessDiagram } from "./ProcessDiagram";
import { InvoiceControlVisual, QualityDemoVisual } from "./ProjectVisual";
import { practiceProjects, solutionGroups } from "@/lib/relaunch-content";

export function ProofSection() {
  return <section className="border-y border-border bg-surface-2/35 py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8"><SectionHead eyebrow="Praxisbeweis" title="Bereits in realen Unternehmensprozessen umgesetzt." intro="LEITIX arbeitet mit internen Abläufen, Belegen und Unternehmensdaten. Deshalb werden Kundenprojekte auf dieser Website anonymisiert dargestellt." />
    <div className="mt-12 grid gap-6 lg:grid-cols-2">
      <Reveal><Showcase title="Intelligent Invoice Control" text="AI-gestützte Erkennung, fachliche Prüfung und operative Zuordnung von Rechnungspositionen."><InvoiceControlVisual /></Showcase></Reveal>
      <Reveal delay={100}><Showcase title="Digital Quality & Training Management" text="Schulungen, Nachweise, Rollen und wiederkehrende Fristen in einem zentralen System."><QualityDemoVisual /></Showcase></Reveal>
    </div><p className="mt-5 text-xs text-muted-foreground">Anonymisierte Demo-Daten. Darstellung real umgesetzter Systeme.</p>
  </div></section>;
}
function Showcase({title,text,children}:{title:string;text:string;children:React.ReactNode}) { return <article className="h-full overflow-hidden rounded-sm border border-border bg-surface"><div className="aspect-[16/9] overflow-hidden border-b border-border bg-background">{children}</div><div className="p-6"><p className="text-[0.62rem] font-semibold tracking-[0.2em] text-primary uppercase">Produktiv umgesetzt</p><h3 className="mt-3 font-display text-xl font-bold text-foreground">{title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{text}</p></div></article>; }

const problems = [
  [FileSearch,"Dokumente werden manuell gelesen und geprüft","Dokumente & Rechnungen","ai-document-intelligence"],
  [Layers3,"Daten werden mehrfach übertragen","Prozesssoftware","business-software"],
  [Database,"Excel oder Papier ist Teil eines Kernprozesses","Operations & Fleet","fleet-operations"],
  [Network,"Informationen liegen in mehreren Systemen","Integration & Automation","data-system-integration"],
] as const;
export function ProblemFinder() { return <section className="py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8"><SectionHead eyebrow="Ausgangspunkt" title="Wo verliert Ihr Prozess heute Zeit?" /><ul className="mt-14 grid gap-px border border-border sm:grid-cols-2">{problems.map(([Icon,title,label,slug],i)=><Reveal as="li" key={title} delay={i*70}><Link to="/loesungen/$slug" params={{slug}} className="group block h-full bg-surface/35 p-7 transition-colors hover:bg-surface sm:p-9"><Icon className="h-6 w-6 text-primary"/><h3 className="mt-6 max-w-md font-display text-lg font-semibold text-foreground">{title}</h3><span className="mt-6 inline-flex items-center gap-2 text-[0.7rem] font-semibold tracking-[0.14em] text-primary uppercase">{label}<ArrowRight className="h-3.5 w-3 transition-transform group-hover:translate-x-1"/></span></Link></Reveal>)}</ul></div></section>; }

const steps=["Prozessaufnahme","Daten & Systeme","Geschäftsregeln","Software / AI","Integration","Betrieb & Weiterentwicklung"];
export function PrincipleSection() { return <section className="radial-depth border-y border-border py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8"><SectionHead eyebrow="LEITIX Prinzip" title="Erst Prozess verstehen. Dann Software bauen." intro="LEITIX beginnt nicht mit einem Tool, sondern mit dem tatsächlichen Ablauf. Welche Entscheidung trifft der Mensch? Welche Daten fehlen? Welche Regeln sind wiederholbar? Erst daraus entsteht die passende Lösung."/><ol className="mt-14 grid gap-px border border-border sm:grid-cols-2 lg:grid-cols-6">{steps.map((s,i)=><li key={s} className="relative bg-background/60 p-5"><span className="text-[0.6rem] tracking-[0.18em] text-primary">0{i+1}</span><p className="mt-4 text-sm font-semibold text-foreground">{s}</p>{i<steps.length-1&&<ArrowRight className="absolute -right-2.5 top-1/2 z-10 hidden h-5 w-5 text-primary lg:block"/>}</li>)}</ol></div></section>; }

export function ProjectTeasers() { return <section className="py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8"><SectionHead eyebrow="Praxisprojekte" title="Reale Lösungen. Vertrauliche Projekte." intro="Die Beispiele basieren auf real umgesetzten oder konkret entwickelten Unternehmenslösungen. Kundendaten, Logos und betriebliche Details wurden anonymisiert oder durch Demo-Daten ersetzt."/><div className="mt-14 grid gap-4 lg:grid-cols-2">{practiceProjects.slice(0,4).map((p,i)=><Reveal key={p.slug} delay={(i%2)*80}><article className="hairline h-full rounded-sm p-6 sm:p-8"><p className="text-[0.62rem] font-semibold tracking-[0.18em] text-primary uppercase">{p.status}</p><h3 className="mt-4 font-display text-xl font-bold text-foreground">{p.title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{p.summary}</p><p className="mt-6 border-l border-primary/50 pl-4 text-sm font-semibold text-foreground">{p.statement}</p></article></Reveal>)}</div><Link to="/praxisprojekte" className="mt-9 inline-flex items-center gap-2 text-sm font-semibold text-primary">Alle Praxisprojekte ansehen <ArrowRight className="h-4 w-4"/></Link></div></section>; }

export function SolutionGroups() { return <section className="border-y border-border bg-surface-2/35 py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8"><SectionHead eyebrow="Lösungen" title="Eine Prozesslücke. Vier Wege zur Lösung."/><ul className="mt-14 grid gap-4 md:grid-cols-2">{solutionGroups.map((s,i)=><Reveal as="li" key={s.key} delay={(i%2)*80}><Link to="/loesungen/$slug" params={{slug:s.slug}} className="group block h-full rounded-sm border border-border p-7 transition-colors hover:border-primary/40 sm:p-9"><span className="text-xs font-semibold text-primary">{s.key}</span><h3 className="mt-5 font-display text-xl font-bold text-foreground">{s.title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{s.text}</p><ArrowRight className="mt-7 h-4 w-4 text-primary transition-transform group-hover:translate-x-1"/></Link></Reveal>)}</ul></div></section>; }

export function IntegrationSection() { return <section className="py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8"><SectionHead eyebrow="Integration statt Austausch" title="Wir ersetzen bestehende Systeme nicht, nur weil wir es können." intro="Viele Unternehmen besitzen bereits ERP, TMS, DMS, Microsoft 365, Datenbanken und Fachanwendungen. LEITIX verbindet bestehende Systeme und ergänzt genau die Prozessschicht, die heute fehlt."/><div className="mt-12"><ProcessDiagram /></div></div></section>; }

export function SecurityTeaser() { return <section className="border-t border-border py-20 sm:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 sm:px-8 lg:grid-cols-[1fr_1.15fr] lg:items-center"><SectionHead eyebrow="Technologie & Sicherheit" title="Passend zur IT-Landschaft. Kontrolliert im Betrieb." intro="Betriebsmodell, Berechtigungen, Datenstandort, Schnittstellen und Wartung werden passend zur Anforderung geplant – nicht pauschal versprochen."/><div className="grid gap-3 sm:grid-cols-2">{["Cloud, On-Premise oder Hybrid","Rollen & Berechtigungen","Audit Log & Recovery","AI mit Human-in-the-Loop"].map(x=><div key={x} className="flex items-center gap-3 border-b border-border py-4 text-sm text-foreground"><CheckCircle2 className="h-4 w-4 text-primary"/>{x}</div>)}<Link to="/technologie-sicherheit" className="mt-3 inline-flex items-center gap-2 text-sm font-semibold text-primary sm:col-span-2">Technologie & Sicherheit ansehen <ArrowRight className="h-4 w-4"/></Link></div></div></section>; }
