import { Check, ArrowRight } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { practiceProjects } from "@/lib/relaunch-content";
import { Reveal } from "./Reveal";
import { InvoiceControlVisual, QualityDemoVisual, WarehouseControlVisual } from "./ProjectVisual";

export function PracticeProjects() {
  return <section className="pb-24 sm:pb-32"><div className="mx-auto max-w-7xl space-y-16 px-5 sm:px-8">{practiceProjects.map((p,index)=><Reveal key={p.slug} as="article"><div id={p.slug} className="grid gap-9 border-t border-border pt-12 lg:grid-cols-[0.9fr_1.1fr] lg:gap-14"><div><p className="text-[0.62rem] font-semibold tracking-[0.18em] text-primary uppercase">{p.status}</p><h2 className="mt-4 font-display text-2xl font-bold text-foreground sm:text-3xl">{p.title}</h2><p className="mt-5 text-base leading-relaxed text-muted-foreground">{p.summary}</p><p className="mt-7 border-l border-primary/60 pl-5 font-display text-lg font-semibold text-foreground">{p.statement}</p><ul className="mt-8 grid gap-3 sm:grid-cols-2">{p.features.map(x=><li key={x} className="flex gap-2.5 text-sm leading-relaxed text-muted-foreground"><Check className="mt-0.5 h-4 w-4 shrink-0 text-primary"/>{x}</li>)}</ul></div><div>{p.slug === "invoice-control" ? <><InvoiceControlVisual/><p className="mt-3 text-xs text-muted-foreground">Anonymisierte Demo-Darstellung eines real umgesetzten Systems.</p></> : p.slug === "warehouse-control" ? <><WarehouseControlVisual/><p className="mt-3 text-xs text-muted-foreground">Eigenständige Demo-Visualisierung des entwickelten Zielprozesses.</p></> : index===1 ? <><QualityDemoVisual/><p className="mt-3 text-xs text-muted-foreground">Anonymisierte Demo-Darstellung eines real umgesetzten Systems.</p></> : <div className="panel rounded-sm p-6 sm:p-8"><p className="text-[0.62rem] font-semibold tracking-[0.2em] text-muted-foreground uppercase">Prozess</p><ol className="mt-6 space-y-3">{p.flow.map((x,i)=><li key={x} className="flex items-center gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-sm border border-primary/40 text-[0.62rem] text-primary">{i+1}</span><span className="text-sm text-foreground">{x}</span>{i<p.flow.length-1&&<ArrowRight className="ml-auto h-3.5 w-3.5 rotate-90 text-muted-foreground"/>}</li>)}</ol></div>}</div></div></Reveal>)}</div><div className="mx-auto mt-16 max-w-7xl px-5 sm:px-8"><Link to="/kontakt" search={{thema:"Praxisprojekt besprechen"}} className="edge-glow inline-flex items-center gap-3 rounded-sm border border-primary/50 bg-primary/10 px-7 py-4 text-sm font-semibold text-foreground">Eigenen Prozess besprechen <ArrowRight className="h-4 w-4"/></Link></div></section>;
}
