/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArbeitsweiseRouteImport } from './routes/arbeitsweise'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as LoesungenRouteImport } from './routes/loesungen'
import { Route as PraxisprojekteRouteImport } from './routes/praxisprojekte'
import { Route as TechnologieSicherheitRouteImport } from './routes/technologie-sicherheit'
import { Route as UeberLeitixRouteImport } from './routes/ueber-leitix'
import { Route as LeistungenIndexRouteImport } from './routes/leistungen.index'
import { Route as LeistungenSlugRouteImport } from './routes/leistungen.$slug'
import { Route as LoesungenIndexRouteImport } from './routes/loesungen.index'
import { Route as LoesungenSlugRouteImport } from './routes/loesungen.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbeitsweiseRoute = ArbeitsweiseRouteImport.update({
  id: '/arbeitsweise',
  path: '/arbeitsweise',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const LoesungenRoute = LoesungenRouteImport.update({
  id: '/loesungen',
  path: '/loesungen',
  getParentRoute: () => rootRouteImport,
} as any)
const PraxisprojekteRoute = PraxisprojekteRouteImport.update({
  id: '/praxisprojekte',
  path: '/praxisprojekte',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologieSicherheitRoute = TechnologieSicherheitRouteImport.update({
  id: '/technologie-sicherheit',
  path: '/technologie-sicherheit',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberLeitixRoute = UeberLeitixRouteImport.update({
  id: '/ueber-leitix',
  path: '/ueber-leitix',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenIndexRoute = LeistungenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeistungenRoute,
} as any)
const LeistungenSlugRoute = LeistungenSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LeistungenRoute,
} as any)
const LoesungenIndexRoute = LoesungenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoesungenRoute,
} as any)
const LoesungenSlugRoute = LoesungenSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LoesungenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arbeitsweise': typeof ArbeitsweiseRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRouteWithChildren
  '/loesungen': typeof LoesungenRouteWithChildren
  '/praxisprojekte': typeof PraxisprojekteRoute
  '/technologie-sicherheit': typeof TechnologieSicherheitRoute
  '/ueber-leitix': typeof UeberLeitixRoute
  '/leistungen/$slug': typeof LeistungenSlugRoute
  '/loesungen/$slug': typeof LoesungenSlugRoute
  '/leistungen/': typeof LeistungenIndexRoute
  '/loesungen/': typeof LoesungenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arbeitsweise': typeof ArbeitsweiseRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/praxisprojekte': typeof PraxisprojekteRoute
  '/technologie-sicherheit': typeof TechnologieSicherheitRoute
  '/ueber-leitix': typeof UeberLeitixRoute
  '/leistungen/$slug': typeof LeistungenSlugRoute
  '/loesungen/$slug': typeof LoesungenSlugRoute
  '/leistungen': typeof LeistungenIndexRoute
  '/loesungen': typeof LoesungenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arbeitsweise': typeof ArbeitsweiseRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRouteWithChildren
  '/loesungen': typeof LoesungenRouteWithChildren
  '/praxisprojekte': typeof PraxisprojekteRoute
  '/technologie-sicherheit': typeof TechnologieSicherheitRoute
  '/ueber-leitix': typeof UeberLeitixRoute
  '/leistungen/$slug': typeof LeistungenSlugRoute
  '/loesungen/$slug': typeof LoesungenSlugRoute
  '/leistungen/': typeof LeistungenIndexRoute
  '/loesungen/': typeof LoesungenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arbeitsweise'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/loesungen'
    | '/praxisprojekte'
    | '/technologie-sicherheit'
    | '/ueber-leitix'
    | '/leistungen/$slug'
    | '/loesungen/$slug'
    | '/leistungen/'
    | '/loesungen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arbeitsweise'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/praxisprojekte'
    | '/technologie-sicherheit'
    | '/ueber-leitix'
    | '/leistungen/$slug'
    | '/loesungen/$slug'
    | '/leistungen'
    | '/loesungen'
  id:
    | '__root__'
    | '/'
    | '/arbeitsweise'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/loesungen'
    | '/praxisprojekte'
    | '/technologie-sicherheit'
    | '/ueber-leitix'
    | '/leistungen/$slug'
    | '/loesungen/$slug'
    | '/leistungen/'
    | '/loesungen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArbeitsweiseRoute: typeof ArbeitsweiseRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  LeistungenRoute: typeof LeistungenRouteWithChildren
  LoesungenRoute: typeof LoesungenRouteWithChildren
  PraxisprojekteRoute: typeof PraxisprojekteRoute
  TechnologieSicherheitRoute: typeof TechnologieSicherheitRoute
  UeberLeitixRoute: typeof UeberLeitixRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbeitsweise': {
      id: '/arbeitsweise'
      path: '/arbeitsweise'
      fullPath: '/arbeitsweise'
      preLoaderRoute: typeof ArbeitsweiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loesungen': {
      id: '/loesungen'
      path: '/loesungen'
      fullPath: '/loesungen'
      preLoaderRoute: typeof LoesungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praxisprojekte': {
      id: '/praxisprojekte'
      path: '/praxisprojekte'
      fullPath: '/praxisprojekte'
      preLoaderRoute: typeof PraxisprojekteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technologie-sicherheit': {
      id: '/technologie-sicherheit'
      path: '/technologie-sicherheit'
      fullPath: '/technologie-sicherheit'
      preLoaderRoute: typeof TechnologieSicherheitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-leitix': {
      id: '/ueber-leitix'
      path: '/ueber-leitix'
      fullPath: '/ueber-leitix'
      preLoaderRoute: typeof UeberLeitixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/': {
      id: '/leistungen/'
      path: '/'
      fullPath: '/leistungen/'
      preLoaderRoute: typeof LeistungenIndexRouteImport
      parentRoute: typeof LeistungenRoute
    }
    '/leistungen/$slug': {
      id: '/leistungen/$slug'
      path: '/$slug'
      fullPath: '/leistungen/$slug'
      preLoaderRoute: typeof LeistungenSlugRouteImport
      parentRoute: typeof LeistungenRoute
    }
    '/loesungen/': {
      id: '/loesungen/'
      path: '/'
      fullPath: '/loesungen/'
      preLoaderRoute: typeof LoesungenIndexRouteImport
      parentRoute: typeof LoesungenRoute
    }
    '/loesungen/$slug': {
      id: '/loesungen/$slug'
      path: '/$slug'
      fullPath: '/loesungen/$slug'
      preLoaderRoute: typeof LoesungenSlugRouteImport
      parentRoute: typeof LoesungenRoute
    }
  }
}

interface LeistungenRouteChildren {
  LeistungenSlugRoute: typeof LeistungenSlugRoute
  LeistungenIndexRoute: typeof LeistungenIndexRoute
}

const LeistungenRouteChildren: LeistungenRouteChildren = {
  LeistungenSlugRoute: LeistungenSlugRoute,
  LeistungenIndexRoute: LeistungenIndexRoute,
}

const LeistungenRouteWithChildren = LeistungenRoute._addFileChildren(
  LeistungenRouteChildren,
)

interface LoesungenRouteChildren {
  LoesungenSlugRoute: typeof LoesungenSlugRoute
  LoesungenIndexRoute: typeof LoesungenIndexRoute
}

const LoesungenRouteChildren: LoesungenRouteChildren = {
  LoesungenSlugRoute: LoesungenSlugRoute,
  LoesungenIndexRoute: LoesungenIndexRoute,
}

const LoesungenRouteWithChildren = LoesungenRoute._addFileChildren(
  LoesungenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArbeitsweiseRoute: ArbeitsweiseRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  LeistungenRoute: LeistungenRouteWithChildren,
  LoesungenRoute: LoesungenRouteWithChildren,
  PraxisprojekteRoute: PraxisprojekteRoute,
  TechnologieSicherheitRoute: TechnologieSicherheitRoute,
  UeberLeitixRoute: UeberLeitixRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
